title: Your awesome title
email: your-email@example.com
description: >- 
  猴子学院
baseurl: "" 
url: "" 
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

